### ISSUE TITLE
Invalid Rooms

### ISSUE THREAD

**Issue by tdsuper** [nv-tlabs/ATISS#16]
Hi,

The script `pickle_threed_future_dataset` and `preprocess_data` both require the parameter **path_to_invalid_scene_ids**, whose default value is **../config/invalid_threed_front_rooms.txt**. 

However, I found that some rooms not listed in invalid_threed_front_rooms.txt are also problematic. One example is MasterBedroom-58086, which is identified by converting the scene json to obj models and opening them in meshlab.

As invalid rooms would ruin the training process, how to easily identify these rooms and record the room ids in invalid_threed_front_rooms.txt?

Another question is how to identify the problematic objects and record jids in black_list.txt.

Thanks!

**Comment by paschalidoud** [comment]
Hi @tdsuper,

Please note that 3D-FRONT dataset has been updated since we released the code, so it is very likely that more invalid rooms appear. Please feel free to send me any additional problematic rooms/objects that you encountered and I am happy to update the ../config/invalid_threed_front_rooms.txt.

To identify the problematic rooms, we applied a set of filtering operations discussed in the supplementary. However, this was a very time-consuming process that required multiple iterations.

Best,
Despoina

**Comment by tdsuper** [comment]
Hi @paschalidoud ,

As the dataset has been updated, could you please share the filtering operation code or re-generate the invalid_threed_front_rooms.txt？If there is no code to share or the filtering process is time-consuming, could you please release the pretrianed model?

Thanks!

**Comment by paschalidoud** [comment]
Ηι @tdsuper,

I apologize for my late reply! You can implement our pre-processing steps by simply calling the corresponding filtering function from https://github.com/nv-tlabs/ATISS/blob/0cce45bd58bf562bd6532b0eb18522700699b89d/scene_synthesis/datasets/common.py#L47 . Please refer to our supplementary for more details.

In case the newly added scenes have different types of problems, they of course won't be discarded using our filtering functions, thus you will have to write your own. 

Regarding releasing pretrained models, we are looking into that.

Best,
Despoina

**Comment by O-Mubarak** [comment]
Hi @tdsuper,
May i ask if you re-generated **invalid_threed_front_rooms.txt*, if yes, can you upload it please so i can take a look?

Thanks.
