### ISSUE TITLE
How to create a custom layout properly?

### ISSUE THREAD

**Issue by kkkkkkkkkkkkkkkin** [nv-tlabs/ATISS#26]
Hi, I am currently trying to create a new floor layout by modifying the boxes.npz data from accepted scene ids, I had to overwrite the old boxes.npz file due to some scene id issues. I am not sure if this is the right step.

Some examples on the scene id issue; running object_suggestion on 'Bedroom-14', 'MasterBedroom-3875' and a custom scene id doesn't work. The code will randomly select another scene instead

Are there any steps I need to take before using certain scenes? Thank you.

**Comment by paschalidoud** [comment]
Hi @kkkkkkkkkkkkkkkin,

You have to modify the code in order to be able to use a custom scene. For example for the case of the `object_suggestion.py` script, simply replace the current_boxes [https://github.com/nv-tlabs/ATISS/blob/master/scripts/object_suggestions.py#L350](https://github.com/nv-tlabs/ATISS/blob/master/scripts/object_suggestions.py#L350), with your custom boxes.

Please note that you will have to modify the scripts a bit to be able to pass your custom bounding boxes, as the current code loads 3D-FRONT scenes, not boxes.

I am closing this issue for now, but feel free to post another question if you have a hard time figuring this out.

Cheers,
Despoina
