### ISSUE TITLE
Executing preprocess_data.py Data Size Missmatch

### ISSUE THREAD

**Issue by KenanSh** [nv-tlabs/ATISS#31]
Hello,
i am getting this issue when executing `preprocess_data.py`  the problem appears when i try to put the path to texture directory to the **3D-FRONT-texture** folder which has this structure:
```
|- 3D-FRONT-texture
| |- 00cc8b1d-b284-4108-a48f-a18c320a9d3a.png
| |- 0b3653b4-8e36-4b16-a01b-7505251c66ae.png
| |- ....
```

and so on

this structure gives this error:

(senior) C:\Users\kenan\Desktop\master\scripts>python preprocess_data.py path_to_output_dir D:\Senior\3D-FRONT D:\Senior\3D-FUTURE-model D:\Senior\3D-FUTURE-model\model_info.json D:\test\3D-FRONT-texture --dataset_filtering threed_front_bedroom   
Applying threed_front_bedroom filtering
Loading dataset  6812 /  6813
Loading dataset with 3879 rooms
Saving training statistics for dataset with bounds: {'translations': (array([-2.7625005,  0.045    , -2.75275  ]), array([2.77844175, 3.6248396 , 2.81854277])), 'sizes': (array([0.03998288, 0.02000002, 0.012772  ]), array([2.8682  , 1.770065, 1.698315])), 'angles': (array([-3.14159265]), array([3.14159265]))} to path_to_output_dir\dataset_stats.txt
Applying threed_front_bedroom filtering
Loading dataset  6812 /  6813
{'translations': (array([-2.7625005,  0.045    , -2.75275  ]), array([2.77844175, 3.6248396 , 2.81854277])), 'sizes': (array([0.0350001 , 0.02000002, 0.012772  ]), array([2.8682  , 1.770065, 1.698315])), 'angles': (array([-3.14159265]), array([3.14159265]))}
Loading dataset with 4041 rooms
2487it [2:13:16,  3.22s/it]
Traceback (most recent call last):
  File "preprocess_data.py", line 271, in <module>
    main(sys.argv[1:])
  File "preprocess_data.py", line 261, in main
    render(
  File "C:\Users\kenan\Desktop\master\scripts\utils.py", line 183, in render
    scene.add(r)
  File "C:\Users\kenan\anaconda3\envs\senior\lib\site-packages\simple_3dviz\scenes.py", line 60, in add
    renderable.init(self._ctx)
  File "C:\Users\kenan\anaconda3\envs\senior\lib\site-packages\simple_3dviz\renderables\textured_mesh.py", line 160, in init
    self.material = self._material
  File "C:\Users\kenan\anaconda3\envs\senior\lib\site-packages\simple_3dviz\renderables\textured_mesh.py", line 203, in material
    self._texture = self._prog.ctx.texture(
  File "C:\Users\kenan\anaconda3\envs\senior\lib\site-packages\moderngl\__init__.py", line 1771, in texture
    res.mglo, res._glo = self.mglo.texture(size, components, data, samples, alignment, dtype, internal_format or 0)
_moderngl.Error: data size mismatch 4194304 != 1048576
__________________________________________________________________________________________________________________________________________
also before that i have this structure the original one is files inside many sub folders as follow:
```
|- 3D-FRONT-texture
| |- 00cc8b1d-b284-4108-a48f-a18c320a9d3a
| | |- texture.png
| |- 0b3653b4-8e36-4b16-a01b-7505251c66ae
| | |- texture.png
| |- ....
```

and so on

this structure when executing gives the error: `PermissionError: [Errno 13] Permission denied`

However when executing this command on demo file in this path` ../demo/floor_plan_texture_images` the code runs correctly but i think i should run the code on the whole textures from dataset not the example ones am i right?

**Comment by paschalidoud** [comment]
Hi @KenanSh,

Am I bit confused with your message and I am not certain what is the problem you are facing... 

Here are some remarks that might be helpful:

- Within the folder `floor_plan_texture_images` there are only textures for the floors not for the 3D-FUTURE objects.
- You are not supposed to change the structure of the files because it is very likely that our code will not be able to process the data properly.
- Since we use [simple-3dviz ](https://simple-3dviz.com/) to parse and visualize meshes with texture, you need to make sure that your changes adhere to simple-3dviz's conventions. For example, if you check the [simple-3dviz ](https://simple-3dviz.com/) implementation for a mesh with texture namely the class defined [TexturedMesh](https://github.com/angeloskath/simple-3dviz/blob/master/simple_3dviz/renderables/textured_mesh.py) you will see that it assumes that whenever the materials are specified as images, the images are named `texture.png`. Therefore, you are not supposed to rename them.

For more details please refer to [the original implementation](https://github.com/angeloskath/simple-3dviz/blob/master/simple_3dviz/renderables/textured_mesh.py#L287).

As this issue is not related to ATISS but to simple-3dviz, I am closing it for now, but feel free to reopen it if you don't figure it out.

Best,
Despi

**Comment by JWFanggit** [comment]
same problem...  can you help me to solve it?
